### ISSUE TITLE
v9-gui: Adding sources in connection profiles

### ISSUE THREAD

**Issue by extrafu** [inverse-inc/packetfence#4127]
It's impossible to add an authentication source when editing a connection profile.

Even if I have about 10 sources defined, none of them are shown and selectable.

**Comment by jrouzierinverse** [comment]
I fixed this yesterday which version are you using?

**Comment by extrafu** [comment]
The latest stuff

**Comment by extrafu** [comment]
@satkunas or @cgx You might want to take a look at the GUI stuff so it's adjusted following @jrouzierinverse's fixes

**Comment by extrafu** [comment]
Looks like it has been partially fixed. I see the sources now but whenever I add one (or more) and try to save I get the error:

<img width="480" alt="Screen Shot 2019-03-27 at 3 07 34 PM" src="https://user-images.githubusercontent.com/1616141/55105116-2a882400-50a2-11e9-9248-0cc7c5b76006.png">

**Comment by satkunas** [comment]
I'm able to create w/o issue. This has likely been fixed elsewhere. 

I'll re-assign to @lzammit for a 3rd-party retest.

**Comment by cgx** [comment]
@jrouzierinverse Indeed, I can create a new connection profile, but I can't edit an existing one. I have the same error message as @extrafu.

**Comment by satkunas** [comment]
Moved to #4257
