### ISSUE TITLE
User login issue

### ISSUE THREAD

**Issue by Ieno77** [inverse-inc/packetfence#5261]
**Describe the bug**
On the web interface, users with access level 'Node Manager / Security Event Manager / User Manager' can't see anything on the GUI

**To Reproduce**
1.Create a User with access level: Node Manager or Security Event Manager or User Manager
2. Log in the GUI with the user you created

**Screenshots**
![buguser](https://user-images.githubusercontent.com/56310726/77935279-3b541280-727f-11ea-9cd9-0dddeb18491f.png)

**Expected behavior**
After login, I have to see the content I have access

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox & Chrome
 - Version  packetfence-9.3.9-20200330095327.130968996.0007.devel.el7.x86_64
                 packetfence-release-2.0.0-20200330095327.130968996.0007.devel.el7.noarch

**Comment by nqb** [comment]
@Ieno77, regarding your screenshot it sounds like a cache issue.

Could you try to clean your caches and check again ?

**Comment by Ieno77** [comment]
> @Ieno77, regarding your screenshot it sounds like a cache issue.
> 
> Could you try to clean your caches and check again ?

Still having the same problem after cleaning my cache (and tryed on Firefox and Chrome)

**Comment by jrouzierinverse** [comment]
This should be solved by 66ee65f0abdfaad22f98f3af5a8d9b36a177fa82

**Comment by jrouzierinverse** [comment]
The problem is httpd.admin is not running

**Comment by extrafu** [comment]
Should it be closed then?

**Comment by Ieno77** [comment]
httpd.admin work now but I still see nothing.
![issueuser](https://user-images.githubusercontent.com/56310726/78060096-f3a1b980-7358-11ea-91bb-881345f3f88d.png)
My server work on:  packetfence-9.3.9-20200331154053.131504969.0007.devel.el7.x86_64

**Comment by cgx** [comment]
Probably a duplicate of #5268.

**Comment by Ieno77** [comment]
> Probably a duplicate of #5268.

Yes it works

**Comment by cgx** [comment]
@Ieno77 can we close this issue?

**Comment by Ieno77** [comment]
@cgx Yes
