### ISSUE TITLE
Unregister a node doesn't work anymore

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5816]
**Describe the bug**
According to [integration tests](https://gitlab.com/inverse-inc/packetfence/-/jobs/749973967#L1577), if you try [to unregister a node using an API call](https://github.com/inverse-inc/packetfence/blob/devel/t/venom/pfservers/common/unreg_node01.yml), it doesn't work anymore.

I guess it's related to merge of recent PR like #5724.

**Comment by nqb** [comment]
Error in `packetfence.log` :
```
Sep 22 07:17:51 pfdeb9dev packetfence: pfperl-api(3182) DEBUG: Calling API with ReAssign request on switch 44:38:39:00:00:12) (pf::enforcement::_vlan_reevaluation)
Sep 22 07:17:51 pfdeb9dev packetfence: pfperl-api(3182) ERROR: call not implemented                                                             (Mojolicious::Plugin::DefaultHelpers::_development)                                                                                                                                                            
Sep 22 07:17:51 pfdeb9dev packetfence: pfperl-api(3182) DEBUG: 500 Internal Server Error (0.118429s, 8.444/s) (Mojolicious::Controller::rendered) 
```

**Comment by fdurand** [comment]
Sep 25 10:32:46 localhost pfqueue: pfqueue(28924) INFO: [mac:c8:60:00:50:cf:0b] Instantiate profile default (pf::Connection::ProfileFactory::_from_profile)
Sep 25 10:32:49 localhost packetfence: pfperl-api(28594) INFO: re-evaluating access (admin_modify called) (pf::enforcement::reevaluate_access)
Sep 25 10:32:49 localhost packetfence: pfperl-api(28594) INFO: Instantiate profile default (pf::Connection::ProfileFactory::_from_profile)
Sep 25 10:32:49 localhost packetfence: pfperl-api(28594) INFO: VLAN reassignment is forced. (pf::enforcement::_should_we_reassign_vlan)
Sep 25 10:32:49 localhost packetfence: pfperl-api(28594) INFO: switch port is (172.20.21.84) ifIndex 2connection type: Wired MAC Auth (pf::enforcement::_vlan_reevaluation)
Sep 25 10:32:49 localhost packetfence: pfperl-api(28594) ERROR: call not implemented
 (Mojolicious::Plugin::DefaultHelpers::_development)

**Comment by jrouzierinverse** [comment]
Please retest

**Comment by nqb** [comment]
Still an issue. I got exact same logs as mentioned in [my previous comment](https://github.com/inverse-inc/packetfence/issues/5816#issuecomment-696552063).

**Comment by jrouzierinverse** [comment]
Please retest should be fixed in b3bc399e5d1e40ab3f5a8c00f297e27ad0a21fb2.

**Comment by nqb** [comment]
I ran an integration tests [job](https://gitlab.com/inverse-inc/packetfence/-/jobs/765272764) on pipeline triggered by this commit. If test failed with [following error](https://gitlab.com/inverse-inc/packetfence/-/jobs/764419921#L1544), it means issue is not fixed.

Edit: I ran again a test because it failed due to #5872

**Comment by nqb** [comment]
[Pipeline](https://gitlab.com/inverse-inc/packetfence/-/jobs/765490296) passed, should be fix.
