### ISSUE TITLE
Suspicious of Denial of service : User "tim" is sending thousands of radius authentication requests

### ISSUE THREAD

**Issue by mickaelidf** [inverse-inc/packetfence#6619]
**Describe the bug**

Eduroam partners are warning us on the following issue: Thousands of radius authentication requests are being sent in a loop by a user named "tim". 
The radius requests are sending each 50 milliseconds to remote radius servers : it is it's huge. 

We never created  the user named "tim". 

**To Reproduce**
1. Open the PacketFence administration web interface and go to 'Configuration→Policies and Access Control→Authentication Sources→ Exclusive Sources '
Local Exclusive Sources and click on New exclusive source then Eduroam. Keep enable Monitor option ( Do you want to monitor this source) on source setting. 

The information to configure that source could be found on the Eduroam platform according to the country where you located.  For France, visit the following link :  https://www.eduroam.fr/specif_tecnik

2.Create the connection profile for local authentication 
Go to Configuration → Policies and Access Control → Connection Profiles → New Connection Profile.

Create a connection profile named Local and external Eduroam authentication Check Automatically register devices then create a SSID filter Eduroam. Make sure to add the Active Directory or Radius source to match on the local users.

3.  Create the connection profile for outbound authentication

Go to Configuration → Policies and Access Control → Connection Profiles → New Connection Profile.

Create the Connection Profile named External Eduroam authentication Check Automatically register devices then create a REALM filter Eduroam. Next, make sure to add the Eduroam source previouly created.

4. Use your computer (Windows 10 20H2) and connect to eduroam SSID.

5. See error your logs and ask your partner if they are receiving  radius requests from user named 'tim'

Example :
15:43:51.075551 IP (tos 0x0, ttl 55, id 63586, offset 0, flags [DF], proto UDP (17), length 71)
    <your FQDN>.35434 >
ix1-pv-u18-eduroamradiusnational-02.renater.fr.radius: RADIUS, length: 43
    Access-Request (1), id: 0xea, Authenticator: 
045a4145f630f22ee1cadc0b9a1376a4
      User-Name Attribute (1), length: 5, Value: tim
      User-Password Attribute (2), length: 18, Value:

**Screenshots**

**Expected behavior**

Packetfence is sending thousands of radius authentication requests are being sent in a loop by a user named "tim". 

The thing is that we didn't have any user named "tim".

We finded the guilty script written in Go language. The file is located at
/go/cmd/pfacct/radius_test.go

This script is sending radius authentication request  each 50 millisecond to remote radius servers : it is it's huge. 

Tim Cooper is the author of this (tim.cooper@layeh.com): https://github.com/inverse-inc/go-radius

**Desktop :**
 - OS: Windows 10;
 - Browser:  chrome 94.0.4606.81 (Build officiel) (64 bits);
 - Version:  20H2;

**Additional context**
It seems that there is link between the script /go/cmd/pfacct/radius_test.go and the monitor option while setting the eduroam or Radius Internal source.

To do so, from 'Configuration→Policies and Access Control→Authentication Sources', click on 'Your Radius Source'.
And the disable Monitor option (Do you want to monitor this source).
[](url)

**Comment by julsemaan** [comment]
Hi,

Thanks for your detailed report.

Its almost impossible that the source of this is in `/go/cmd/pfacct/radius_test.go` since this file is only used during unit tests (as per Golang's standard)

The source of this comes from pfstats where it is monitoring the eduroam servers by sending RADIUS access-requests to it

AFAIK, this has been addressed in our recent releases so my guess is that you're running an old version of PF (which I couldn't find in your description)

In order to just stop this, go in your eduroam source configuration in the admin panel of PacketFence and disable 'Monitor' and restart the `pfstats` service. This will disable this mechanism completely.

The commit that fixes this in our code base is: https://github.com/inverse-inc/packetfence/commit/6ceeee643748696c7d580c16e072fbf4ce61cc49

It is included in PF 10.2+ so my guess is that you're running a version lower than that and will need to just disable the check entirely as described above.

Cheers,

**Comment by mickaelidf** [comment]
Hi,

Many thanks for your reply and your guidance.
First I'm running Packetfence 10.1.0.

My test result:
I disableed 'Monitor' and restarted the pfstats service:
/usr/local/pf/bin/pfcmd service pfstats restart.
But I made a tcpdump and I'm still seeing a user named "tim"  sending
radius requests.

Question:
For Packetfence 10.1.0, where is located the script for this mechanism ?
I guess  the script /usr/local/pf/go/stats/main.go ?

Cheers.
Mickael BOUBALA

Le jeu. 14 oct. 2021 à 13:31, Julien Semaan ***@***.***> a
écrit :

**Comment by julsemaan** [comment]
That's not a script, you'll need to recompile the binary after changing it.

We've applied the workaround to many deployments with success so I'm not sure what could be missing, perhaps @fdurand can provide input

**Comment by fdurand** [comment]
Just run pf-maint.pl in /usr/local/pf/addons/ and restart the service.
This fix has been added a long time ago in the maintenance/10.1 branch (https://github.com/inverse-inc/packetfence/commit/0217383582d230b61c5b7582bd8ef8ded1754008#diff-2dc072e7fe95180ff16e77f893dd15629f158457980035036ae77323021da4ed)
